name: livro_registro
description: Livro de registro da Escola Bíblica Dominical (EBD) — projeto recuperado do APK instalado.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  share_plus: ^10.0.2
  printing: ^5.13.4
  pdf: ^3.11.1
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  intl: 0.20.2
  uuid: ^4.5.1
  equatable: ^2.0.5
  path: ^1.9.0
  supabase_flutter: ^2.16.0
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3
  local_auth: ^3.0.2
  flutter_secure_storage: ^10.3.1
  confetti: ^0.8.0
  flutter_dotenv: ^6.0.1
  http: ^1.6.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/bible/
    - assets/quiz/
    - .env.example

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_foreground: assets/icon/app_icon_fg.png
  adaptive_icon_background: "#F7F2E7"
  remove_alpha_ios: true
